- Example/Podfile.lock
- Example/SuperAwesome/Base.lproj/Main.storyboard
- Example/SuperAwesome/ViewController.m
- SuperAwesome.podspec
Link of the JIRA tickets the PR relates to. 
[AA-3724](https://jira.superawesome.tv/browse/AA-3724)
Add the new SAAgeCheck/isMinor to the AA SDK. 
**NOTE**
The current state of the API only returns
```
{
"country": "gb",
"age": 13
}
```
The implementation however is already in place for
```
{    
"country": "gb",    
"consentAgeForCountry": 13,    
"age": 6,   
"isMinor": true
}
```
So the response might be misleading while it waits for the API update
Attach any screenshot or .gif file to show how the PR fixes an issue or the new behaviour introduced by it.
> Added SAAgeCheck as a dependency. Added UI to show results.

- Example/SuperAwesome/Base.lproj/Main.storyboard
- Example/SuperAwesome/Info.plist
- Example/SuperAwesome/ViewController.m
- Pod/Classes/SABannerAd.m
- Pod/Classes/SAInterstitialAd.m
- Pod/Classes/Video/VideoAd.swift
- Pod/Classes/Video/VideoViewController.swift
##JIRA
https://jira.superawesome.tv/browse/KWS-7613
##Description
* Fixes for the missing close button on interstitials
* Fixed presentation type.
##Screenshots
> More Fixes for iOS 13

- Example/SuperAwesome/ViewController.m
- Pod/Classes/SABannerAd.m
- Pod/Classes/Video/VideoAd.swift
- Pod/Classes/Video/VideoClick.swift
- Pod/Classes/Video/VideoViewController.swift
https://jira.superawesome.tv/browse/KWS-7683
* Added a bumper for the safe ad logo link
* Added parental gate to the safe ad logo link if enabled
Parental gate disabled:
Parental gate enabled:
> KWS-7683: Bumper for the safe ad logo link

- SuperAwesome.podspec
updated podspec versions for SAWebPlayer (1.4.1) and SAVideoPlayer (2.0.0-beta7) and updated this pod version to 7.1.1
NOTE, the dependencies above do not yet exist.
> updated podspec

- Pod/Classes/CommonUI/LayoutUtils.swift
- Pod/Classes/Libs/SAVideoPlayer/AwesomeVideoPlayer.swift
- Pod/Classes/Video/AdSocialVideoPlayerControlsView.swift
https://rukkaz.atlassian.net/browse/RUK-284
* Added safe area constraints to VideoAd controls
* Added a guard statement to the isFullscreen property in `setMaximised` and `setMinimised` of the `AwesomeVideoPlayer` class
> RUK-284: Added Safe area constraints for VideoAd controls

- Pod/Sources/UI/Banner/BannerView.swift
- Pod/Sources/UI/Banner/WebView.swift
- Pod/Sources/UI/Interstitial/InterstitialAd.swift
> Ensure all inline docs are properly formatted

- Example/Podfile.lock
- Example/SuperAwesomeExample.xcodeproj/project.pbxproj
- Pod/Classes/SuperAwesome.h
- Pod/Plugin/Unity/SAUnityAwesomeAds.mm
- Pod/Plugin/Unity/SAUnityBannerAd.mm
- Pod/Plugin/Unity/SAUnityBumperPage.mm
- Pod/Plugin/Unity/SAUnityCallback.h
- Pod/Plugin/Unity/SAUnityCallback.mm
- Pod/Plugin/Unity/SAUnityInterstitialAd.mm
- Pod/Plugin/Unity/SAUnityVideoAd.mm
- SuperAwesome.podspec
Made some changes to the Unity files so they're compatible with the current SDK code and they can talk to Unity.
> fix(unity): fix current unity build

- Example/Podfile.lock
- Pod/Classes/SAVersion.m
- SuperAwesome.podspec
- SuperAwesomeAdMob.podspec
> Feature/publish 8.1.4

- Example/SuperAwesome/ViewController.m
Added same test placements from Android to iOS. Banner, Interstitial (Standard) and Direct Video all currently work, but the two KSF placements don't work right now.
Spoke to @gunhansancar and we'll get these new IDs merged in and then go from there so we can both test using the same placements
> Aag 1590 test app placements

- Pod/Classes/Common/Components/AdQueryMaker.swift
- Pod/Classes/Common/Components/CustomEncoder.swift
- Pod/Classes/Common/DI/CommonModule.swift
- Pod/Classes/Common/Model/EventModels.swift
fix: AAG-1643 double encoding for the ad events and also fix the event names
> AAG-1643 Fix for double encoding and event names

- Pod/Classes/Common/Components/AdProcessor.swift
- Pod/Classes/Common/Components/HtmlFormatter.swift
- Pod/Classes/Common/Model/Constants.swift
- Pod/Classes/Common/Model/CreativeModels.swift
Fix: KSF ads not loading issue
> AAG-1819 KSF ads not loading issue

- Example/SuperAwesome/MainViewController.swift
- Pod/Classes/Video/VideoAd.swift
Updating placements with safe ad approved KSF campaigns and adding a log for `adEmpty` callback
> Aag 1842 safe ad placements

- Pod/Classes/SAVersion.m
- SuperAwesome.podspec
- SuperAwesomeAdMob.podspec
> update: version to 8.3.0

- CHANGELOG.md
- Pod/Classes/SAVersion.m
- SuperAwesome.podspec
- SuperAwesomeAdMob.podspec
update: release version to 8.3.3
> update: release version to 8.3.3

- CHANGELOG.md
- SuperAwesome.podspec
- SuperAwesomeAdMob.podspec
This PR updates the podspecs for `8.3.4`. After this is merged I will tag the commit where the `Creative` - `Payload` fix was merged.
> release(): 8.3.4

- Example/SuperAwesome/MainViewController.swift
- Example/SuperAwesomeExampleTests/Common/Components/AdQueryMakerTests.swift
- Example/SuperAwesomeExampleTests/Common/Mocks/AdDataSourceMock.swift
- Example/SuperAwesomeExampleTests/Common/Mocks/AdQueryMakerMock.swift
- Example/SuperAwesomeExampleTests/Common/Mocks/MockFactory.swift
- Example/SuperAwesomeExampleTests/Common/Network/AwesomeAdsTargetTests.swift
- Pod/Classes/Base/SDK/AwesomeAds.swift
- Pod/Classes/Common/Components/AdQueryMaker.swift
- Pod/Classes/Common/DI/CommonModule.swift
- Pod/Classes/Common/DI/Configuration.swift
- Pod/Classes/Common/DataSources/AwesomeAdsApiDataSource.swift
- Pod/Classes/Common/Network/AwesomeAdsApi.swift
- Pod/Classes/Common/Network/QueryBundle.swift
- Pod/Classes/Common/Repositories/AdRepository.swift
- Pod/Classes/Common/Repositories/EventRepository.swift
- Pod/Classes/Network/DataSources/MoyaAwesomeAdsApiDataSource.swift
- Pod/Classes/Network/Network/AwesomeAdsTarget.swift
Allowing optional options to be passed through when initialising SDK to track against events
> add: optional parameters support to iOS SDK

- CHANGELOG.md
- SuperAwesome.podspec
- SuperAwesomeAdMob.podspec
- docs/.circleci/config.yml
- docs/_config.yml
feat(): Removed remaining mentions of master, bumped the version to 8.3.6, updated the changelog
> 8.3.6 Release

- docs/_data/toc.yml
- docs/_docs/examples.md
- docs/_docs/initial-setup.md
- docs/_docs/video-ads.md
This PR adds documentation for SDK info, the options dictionary and the immediate close button
> Public documentation updates

- CHANGELOG.md
- SuperAwesome.podspec
- SuperAwesomeAdMob.podspec
This PR bumps the version to `8.3.8`
> Bumped versions to 8.3.8

- Pod/Classes/Base/SDK/AwesomeAds.swift
fix(): objc tag for the AwesomeAds class to enable access using the string name
> fix(): objc tag for the AwesomeAds class to enable access

- CHANGELOG.md
- SuperAwesome.podspec
- SuperAwesomeAdMob.podspec
Release a new version for 8.3.9
> release 8.3.9

- .github/PULL_REQUEST_TEMPLATE.md
> NO-JIRA: Added PR template

- Pod/Classes/UI/Managed/SAManagedAdViewController.swift
[AAG-2735]
This PR adds an accessibility id that's used in this PR: https://github.com/SuperAwesomeLTD/sa-ad-smoke-test-sdk/pull/76
n/a
[AAG-2735]: https://superawesomeltd.atlassian.net/browse/AAG-2735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(): added accessibility id

- .swiftlint.yml
- Adapters/AdMob/Classes/SAAdMobAdapter.swift
- Adapters/AdMob/Classes/SAAdMobBannerAd.swift
- Adapters/AdMob/Example/Podfile.lock
- SuperAwesomeAdMob.podspec
[AAG-2724]
Updating podspec to release a new version for admob plugin
[AAG-2724]: https://superawesomeltd.atlassian.net/browse/AAG-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(): update podspec

- CHANGELOG.md
- Pod/Classes/Common/Model/Version.swift
> chore(): release 8.5.1

- Adapters/AdMob/Classes/SAAdMobInterstitialCustomEvent.m
- Adapters/AdMob/Classes/SAAdMobRewardedAd.h
- Adapters/AdMob/Classes/SAAdMobRewardedAd.m
- Adapters/AdMob/Classes/SAAdMobVideoMediationAdapter.h
- Adapters/AdMob/Classes/SAAdMobVideoMediationAdapter.m
- Adapters/AdMob/Example/Podfile.lock
- SuperAwesomeAdMob.podspec
Had to update minimum ios version to `11.0` from `10.0` for AdMob integration
> chore(): fixing imports

- Example/SuperAwesomeExampleTests/Common/Mocks/MockFactory.swift
- Example/SuperAwesomeExampleTests/Common/Model/AdModelTests.swift
- Pod/Classes/Common/Model/AdModels.swift
fix(): remove unused fields from Ad model which causes issues when mapping json to object
> fix(): remove unused fields from Ad model

- Example/Podfile
- Example/Podfile.lock
- Pod/Classes/Common/Extensions/UIViewController+Extensions.swift
- Pod/Classes/UI/Banner/BannerView.swift
- Pod/Classes/UI/Common/BumperPage.swift
- Pod/Classes/UI/Common/ParentalGate.swift
[AAG-2774]
This PR modifies how the Parent Gate and Bumper screens are presented, instead of using a UIWindow, they are now presented on the top most view controller. This implementation enables these features to work with SwiftUI.
Interstitial / Banner
https://user-images.githubusercontent.com/618350/214373836-d9472a50-530c-4dec-b275-a11683da259f.mov
Video: 
https://user-images.githubusercontent.com/618350/214599507-128455f4-9824-4fdd-867e-1904b3bb704a.mov
[AAG-2774]: https://superawesomeltd.atlassian.net/browse/AAG-2774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AAG-2774: iOS: UIWindow Removal

- CHANGELOG.md
- Pod/Classes/Common/Model/Version.swift
> chore(): release 8.5.2

- .circleci/config.yml
NO-JIRA
Modified iOS releases to not use a v prefix on tags.
n/a
> NO-JIRA: Modified iOS releases to not use a v prefix on tags

- .circleci/config.yml
NO-JIRA
Added Tag format to semantic release
n/a
> NO-JIRA: Added Tag format to semantic release

- .circleci/config.yml
NO-JIRA
Removed the tag format from Semantic release statements in CircleCI
n/a
> NO-JIRA: Removed the tag format from Semantic release statements in CircleCI

- .circleci/config.yml
NO-JIRA
Modified the GH token generation to persist the env variables
n/a
> NO-JIRA: Modified the GH token generation to persist the env variables

- .circleci/config.yml
NO-JIRA
Added secure url to git commands to use correct token instead of the circle ci token
n/a
> NO-JIRA: Added secure url to git commands to use correct token.

- .github/CODEOWNERS
NO-JIRA
Updated code owners for pull requests
n/a
> NO-JIRA: Updated code owners for pull requests

- Pod/Classes/Common/Model/Version.swift
NO-JIRA
Reverted version number to 8.5.3 as it was incremented too high by the ci due to issues
n/a
> NO-JIRA: Reverted version number to 8.5.3

- .circleci/config.yml
NO-JIRA
Fixed missing git pull step for semantic release
n/a
> NO-JIRA: Fixed missing git pull step for semantic release

- Pod/Classes/Common/Model/Version.swift
NO-JIRA
Reverted version 8.5.3 for re-release
n/a
> NO-JIRA: Reverted version 8.5.3 for re-release

- SuperAwesome.podspec
- SuperAwesomeAdMob.podspec
NO-JIRA
Updated authors to remove Gabriel Coman 😢 
n/a
> NO-JIRA: Updated authors to remove Gabriel Coman

- .gitignore
- Example/Podfile.lock
- Example/SuperAwesomeExample.xcodeproj/project.pbxproj
- Pod/Classes/UI/Banner/BannerView.swift
- Pod/Classes/UI/Interstitial/InterstitialAd.swift
- Pod/Classes/UI/Video/VideoAd.swift
[AAG-2819](https://superawesomeltd.atlassian.net/browse/AAG-2819)
This PR adds wrappers for the load with options methods for Obj-C and Objective C++ (Unity) to avoid breaking changes
n/a
[AAG-2819]: https://superawesomeltd.atlassian.net/browse/AAG-2819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(): Added wrapper methods for obj-c / Unity compatibility

- Example/Podfile.lock
- Pod/Classes/Network/DI/NetworkModule.swift
- Pod/Classes/Network/DataSources/AFNetworkDataSource.swift
[AAG-2861]
Additional caching policy tweaks for Moya requests
n/a
[AAG-2861]: https://superawesomeltd.atlassian.net/browse/AAG-2861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AAG-2861: Additional caching policy tweaks for Moya requests

- .circleci/config.yml
NO-JIRA
Added force push for Semantic Release
n/a
> Added force push for Semantic Release

- .circleci/config.yml
NO-JIRA
Removed Force push for semantic release
n/a
> Removed Force push for semantic release

- fastlane/Fastfile
NO-JIRA
Removed GH token code for fetching continuous integration repo.
n/a
> chore(): Removed GH token code for fetching continuous integration repo.

- Example/SuperAwesomeExampleUITests/Stories/BannerUITests.swift
[[AAG-3105](https://superawesomeltd.atlassian.net/browse/AAG-3105)]
Testing the banner UI tests on CI by reverting previous wait changes
n/a
[AAG-3105]: https://superawesomeltd.atlassian.net/browse/AAG-3105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(): testing fixes for banner UI tests on CI

- IronSourceExample/SuperAwesomeIronSourceExample/SuperAwesomeIronSourceExample/IronSourceViewController.swift
NOJIRA
Changes the app key to the shared account one.
n/a
> chore(examples): swap app key

- .circleci/config.yml
[AASDK-717]
New Gha Token Generator Orb in CCI config.yml file 
n/a
[AASDK-717]: https://superawesomeltd.atlassian.net/browse/AASDK-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> New Gha Token Generator Orb in CCI config.yml file

- .circleci/config.yml
NO-JIRA
Disabled CI on this Repo as it is no longer used.
n/a
> chore(CI): Disabled CI
