Pod/Classes/Libs/SAVideoPlayer/AwesomeVideoFullscreenPlayer.swift

##JIRA
n/a
##Description
When rotating the Fullscreen video player, it would always auto rotate to Landscape left and completely rotate the screen to that orientation even when rotating to landscape right resulting in a flipped video.
I have fixed this by reading the orientation of the screen at the time the full screen video player appears, if the full screen video player is presented and the device is in portrait it will default to landscape left unless the initial orientation property is changed. 
The default orientation is ignored on the iPad.
##Screenshots
**Before:**
**After:**

Fixed full screen video player initial orientation issue

---

Adapters/AdMob/Classes/SAAdMobRewardedAd.h
Adapters/AdMob/Classes/SAAdMobRewardedAd.m
Adapters/AdMob/Classes/SAAdMobVideoMediationAdapter.h
Adapters/AdMob/Classes/SAAdMobVideoMediationAdapter.m
Adapters/AdMob/Example/Podfile.lock
Adapters/AdMob/Example/SuperAwesomeAdMob/AdMobViewController.swift
SuperAwesomeAdMob.podspec

Update AdMob Rewarded Video Ads to the latest version, Remove deprecated `RewardBasedVideoAd` and use `RewardedAd`

Update AdMob Rewarded Video Ads to the latest version

---

Example/Podfile.lock
SuperAwesome.podspec

`SwiftyXMLParser` causes Podfile installation failure, updating to the latest version

fix: #145 SwiftyXMLParser causes Podfile installation failure by updating

---

Pod/Classes/UI/Common/AdController.swift
Pod/Classes/Video/VideoAd.swift
Pod/Classes/Video/VideoViewController.swift

Adding debug logs for:
- adLoaded
- adShown
- adClicked
- adEnded
- adClosed
- adAlreadyLoaded
@gunhansancar:
**Please let me know if my use of logger anywhere isn't right** (my first time doing mobile development 🙂) - the logs are coming through correctly but unsure on if the logger library is being defined correctly, what log level to use, and if they need tags.
Video below showing logs being generated for all of the above, except `adAlreadyLoaded` - we may not need to test this in QA.
https://user-images.githubusercontent.com/48458132/152389448-752693a2-87a6-461f-b71f-2ae199c9f5f6.mov

chore(): add debug logs for adLoaded, adShown, adClicked, adClosed and adEnded

---

Pod/Classes/Common/DI/CommonModule.swift
Pod/Classes/Common/Repositories/EventRepository.swift
Pod/Classes/Libs/SAEvents/SAEvents.m

Adding debug logs for event tracking:
- `moat` (video)
- `impression`
- `impression` (video)
- `viewable_impression`
- `click`
- `video_click`
- `first_quartile`
- `midpoint`
- `third_quartile`
- `complete`
Only event triggers I couldn't find were for `moat` (display) and `dwell_time`. I found trigger methods defined [here](https://github.com/SuperAwesomeLTD/sa-mobile-sdk-ios/blob/805fd130bc9ad88cc5cc2e0aa1aca8de6201efc8/Pod/Classes/Libs/SAEvents/SAEvents.m#L172) and [here](https://github.com/SuperAwesomeLTD/sa-mobile-sdk-ios/blob/3dbc505f75a2631a7bb263db34d9a2a5261b7988/Pod/Classes/Common/Repositories/EventRepository.swift#L61) respectively, but they aren't called anywhere in the code?

Aag 1592 event tracking calls

---

Pod/Plugin/Unity/SAUnityBumperPage.mm

Adding back the removed `SuperAwesomeUnityBumperOverrideName` to the Unity iOS codes

Bugfix: Add back SuperAwesomeUnityBumperOverrideName

---

Pod/Classes/Libs/SAVideoPlayer/AwesomeVideoFullscreenPlayer.swift

This PR fixes an issue where the `AwesomeVideoFullscreenPlayer` wouldn't fully fill the screen in some circumstances.

fix(): The AwesomeVideoFullscreenPlayer would occasionally not expand to fill the fullscreen

---

Example/SuperAwesome/MainViewController.swift
Example/SuperAwesomeExample.xcodeproj/project.pbxproj
Example/SuperAwesomeExample.xcodeproj/xcshareddata/xcschemes/SuperAwesome.xcscheme
Example/SuperAwesomeExample.xcodeproj/xcshareddata/xcschemes/SuperAwesomeExample.xcscheme
Example/SuperAwesomeExampleUITests/VideoAdUITests.swift
Pod/Classes/Common/Model/Constants.swift
Pod/Classes/Common/State/CloseButtonState.swift
Pod/Classes/UI/Common/AdConfig.swift
Pod/Classes/UI/Video/AdSocialVideoPlayerControlsView.swift
Pod/Classes/UI/Video/ChromeComponents.swift
Pod/Classes/UI/Video/VideoAd.swift
Pod/Classes/UI/Video/VideoViewController.swift

This PR adds the ability to display the close button immediately via the method: `enableCloseButtonNoDelay()`.
It seemed logical that `enableCloseButton` and `disableCloseButton` should still have the expected behaviour so both need to be set to remove the delay which I've documented. Once this is merged I'll need to update the SDK documentation too.
https://user-images.githubusercontent.com/30452349/172438798-359ea9d2-7967-41bd-9ccb-eee24155db59.mp4

Added the ability to display the close button immediately and UI tests for the behaviour

---

Example/Podfile.lock
Example/SuperAwesomeExample.xcodeproj/project.pbxproj
Example/SuperAwesomeExampleTests/UI/Common/AdControllerTests.swift
Pod/Classes/UI/Video/VideoViewController.swift

This sets the callback property on the `AdController` for the `VideoViewController` to ensure that events are dispatched back to the `VideoAd` callback.
https://user-images.githubusercontent.com/30452349/179216388-afd352b3-6cfa-4cdd-a7ac-1ff603d7efc9.mov

Added missing callback to the AdController

---

Example/Podfile.lock
Example/SuperAwesomeExampleTests/Common/Components/SdkInfoTests.swift
Pod/Classes/Common/Components/SdkInfo.swift
Pod/Classes/Common/DI/CommonModule.swift
Pod/Classes/Common/Model/Version.swift
SuperAwesome.podspec

fix(): SDK version was fetched from the bundle which was a problem on non framework builds. Now the version is read in a file called `Version.swift` which is also parsed inside the `podspec` file as well. Therefore, the version information will be set in single place.

fix(): SDK version was fetched from the bundle

---

docs/_data/toc.yml
docs/_docs/bumper-page.md
docs/_docs/parental-gate.md

This PR updates the documentation for disabling the bumper and the parental gate.

chore(): update documentation for disabling the bumper and the parental gate

---

Example/Podfile.lock
Example/SuperAwesome/MainViewController.swift
Example/SuperAwesomeExampleUITests/InterstitialUITests.swift
Example/SuperAwesomeExampleUITests/VideoAdUITests.swift

This PR updates the example app with a new placement for Non-KSF VPAID testing

chore(): example app update for VPAID testing

---

Adapters/AdMob/Classes/SAAdMobBannerCustomEvent.m
Adapters/AdMob/Classes/SAAdMobExtras.h
Adapters/AdMob/Classes/SAAdMobExtras.m
Adapters/AdMob/Classes/SAAdMobInterstitialCustomEvent.m
Adapters/AdMob/Classes/SAAdMobRewardedAd.m
Adapters/AdMob/Classes/SAAdMobVideoMediationAdapter.m
Adapters/AdMob/Example/Podfile.lock
Adapters/AdMob/Example/SuperAwesomeAdMob.xcodeproj/project.pbxproj
Adapters/AdMob/Example/SuperAwesomeAdMob/AdMobViewController.swift
Example/Podfile.lock
SAAdMobAdapter.swift
SAAdMobBannerAd.swift
SuperAwesomeAdMob.podspec

Refactor admob integration code Part 1 which includes converting the BannerAd to Swift.
The second part will contain the same for interstitial and video ads
Also this PR fixes compile issue when we upgrade the dependency of `SuperAwesome` sdk from 7.x to 8.5
[AAG-2724]
Refactor admob integration code to support newer versions of `AwesomeAds`
[AAG-2724]: https://superawesomeltd.atlassian.net/browse/AAG-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(): refactor admob integration code Part 1

---

Example/Podfile
Example/Podfile.lock
Pod/Classes/UI/Banner/BannerView.swift

[AAG-2775]
This PR updates the constraints for the embedded Web View in the BannerView, instead of letting this view decide it's width and height, we strictly specify the size using the parent view frame, I don't understand how this worked prior.
⚠️  **IMPORTANT:** This PR contains a compile fix, the Firebase dependencies in the example pod file were not version locked and due to this there were compile errors in another Google framework. ⚠️ 
[AAG-2775]: https://superawesomeltd.atlassian.net/browse/AAG-2775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AAG-2775: iOS Banner Webview constraints

---

.circleci/config.yml
Example/SuperAwesomeExample.xcodeproj/xcshareddata/xcschemes/SuperAwesomeExample - UITests.xcscheme

[AAG-2816]
This PR adds a new scheme to the iOS project for UI tests only, unit tests are run against the main example app scheme.
I have also cleaned up the workflows to make them more explicit and easier to maintain.
The CRON job runs UI tests every weekday morning at 7am.
When building UI tests, if you prefix the branch with: `ui-tests/` e.g. `ui-tests/aag-xxxx-this-is-a-ui-test` the UI test job will run on that branch when a pull request is raised.
[AAG-2816]: https://superawesomeltd.atlassian.net/browse/AAG-2816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AAG-2816: UI test split and CRON job for UI tests on CI

---

Adapters/AdMob/Classes/SAAdMobAdapter.h
Adapters/AdMob/Classes/SAAdMobAdapter.m
Adapters/AdMob/Classes/SAAdMobBannerAd.m
Adapters/AdMob/Classes/SAAdMobBannerCustomEvent.h
Adapters/AdMob/Classes/SAAdMobInterstitialAd.m
Adapters/AdMob/Classes/SAAdMobInterstitialCustomEvent.h
Adapters/AdMob/Classes/SAAdMobRewardedAd.m
Adapters/AdMob/Classes/SAAdMobVideoMediationAdapter.h
Adapters/AdMob/Example/Podfile.lock
Example/SuperAwesomeExampleTests/Common/Mocks/AdProcessorMock.swift
Example/SuperAwesomeSwiftUIExample/Views/Screens/FeatureDetailView.swift
Pod/Classes/Common/Components/AdQueryMaker.swift
Pod/Classes/Common/PropertyWrappers/CodableExcluded.swift
Pod/Classes/UI/Video/VideoAd.swift

[AAG-2844]
fix(): AdMob custom adapters so that the correct events are passed through the admob plugin from the awesome ads sdk
- Adds a new class to combine different type of custom ad formats called `SAAdMobAdapter` to align with Android SDK
- Deprecated the following custom event classes and instead suggested to use the new `SAAdMobAdapter` `SAAdMobBannerCustomEvent`
`SAAdMobInterstitialCustomEvent`
`SAAdMobVideoMediationAdapter`
[AAG-2844]: https://superawesomeltd.atlassian.net/browse/AAG-2844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(): AdMob custom adapters

---

Pod/Classes/Network/DataSources/AFNetworkDataSource.swift

[AAG-2861]
Changed the caching policy on all network requests made by the SA SDK to ignore cache on both local and remote.
The default Alamofire caching policy of load from disk was enabled, this is now set to ignore both local and remote caches.
n/a
[AAG-2861]: https://superawesomeltd.atlassian.net/browse/AAG-2861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AAG-2861: Changed the caching policy on all network requests

---

Pod/Classes/Common/State/CloseButtonState.swift

[AAG-2880)]
This PR adds a close button state helper to set the close button state from the Unity Objective-C wrapper. It follows the approach of the `OrientationHelper`. The idea is that the bridging Objective-C takes an `int` from the C#.
n/a

chore(): Added a helper to get a CloseButtonState from an int

---

.circleci/config.yml

NO-JIRA
Locked in Circle CI macos.x86.medium.gen2 resource class
n/a

fix(CI): Locked in Circle CI macos.x86.medium.gen2 resource class

---

SuperAwesome/Classes/UI/Interstitial/InterstitialAd.swift

[AASDK-318]
- New function doesn't take placementId as param
- Marks old function as deprecated
[AASDK-318]: https://superawesomeltd.atlassian.net/browse/AASDK-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(interstitial): create new hasAdAvailable function
